apiVersion: ai.sap.com/v1alpha1
kind: ExecutionTemplate
metadata:
  name: forecast-pipeline-v1
  annotations:
    scenarios.ai.sap.com/id: "vertriebs-forecast"
    scenarios.ai.sap.com/name: "Progroup Vertriebs Prognose"
    executables.ai.sap.com/id: "forecast-exec"
    executables.ai.sap.com/name: "Absatz-Prognose-Algorithmus"
spec:
  template:
    spec:
      containers:
        - name: forecaster
          image: "python:3.9"
          command: ["python", "-c", "print('Hello Progroup')"]
