apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: progroup-forecast-pipeline
  annotations:
    scenarios.ai.sap.com/name: "Progroup Vertriebs Prognose"
    executables.ai.sap.com/name: "Absatz-Prognose-Algorithmus"
  labels:
    scenarios.ai.sap.com/id: "vertriebs-forecast"
    executables.ai.sap.com/id: "forecast-exec"
    ai.sap.com/version: "0.1.0"
spec:
  inputs:
    artifacts:
      - name: "sales-data"
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations:
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "100"
        autoscaling.knative.dev/targetBurstCapacity: "70"
      labels:
        ai.sap.com/instanceType: "g6e.4xlarge"
    spec:
      predictor:
        containers:
          - name: "forecaster"
            image: "python:3.9"
            command: ["python", "-c"]
            args:
              - |
                import os
                print("Starte Progroup Forecast Analyse...")
                # Deine Logik hier
            volumeMounts:
              - name: "sales-data-volume"
                mountPath: "/input/sales-data/"
        volumes:
          - name: "sales-data-volume"
            target:
              artifactName: "sales-data"
